# Format: type|label|key|arg1|arg2
# type:
#   android  arg1 = Android component (package/activity)
#   terminal arg1 = shell command, arg2 = tmux window name (optional)
#
# Example:
# terminal|btop |B|btop|btop

android|YouTube 󰗃|y|app.revanced.android.youtube/com.google.android.youtube.app.honeycomb.Shell$HomeActivity|
android|Browser 󰖟|b|com.brave.browser_nightly/com.google.android.apps.chrome.Main|
android|WhatsApp 󰖣|w|com.whatsapp/com.whatsapp.Main|
android|Mihon 󰄛|t|app.mihon/eu.kanade.tachiyomi.ui.main.MainActivity|
android|Solid Explorer 󰉋|f|pl.solidexplorer2/pl.solidexplorer.SolidExplorer|
android|Settings 󰒓|s|com.android.settings/com.android.settings.Settings|
android|App Search 󱡴|l|net.nhiroki.bluelineconsole/net.nhiroki.bluelineconsole.applicationMain.MainActivity|
android|Lock Screen 󰌾|z|com.tiendnm.zukulock/com.tiendnm.zukulock.MainActivity|
terminal|btop |B|rish -c 'XDG_CONFIG_HOME=/data/local/tmp/btop-mini /data/local/tmp/btop/btop --force-utf'|btop
terminal|kew 󰝚|k|dbus-launch kew|kew
terminal|codex 󰚩|c|codex|codex
